# Generated by Django 5.2.5 on 2025-11-04 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Nível')),
                ('deposit_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Depósito')),
                ('daily_gain', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Diário')),
                ('monthly_gain', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Mensal')),
                ('cycle_days', models.IntegerField(verbose_name='Ciclo (dias)')),
                ('image', models.ImageField(upload_to='level_images/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Nível',
                'verbose_name_plural': 'Níveis',
            },
        ),
        migrations.CreateModel(
            name='PlatformBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('IBAN', models.CharField(max_length=50, verbose_name='IBAN')),
                ('account_holder_name', models.CharField(max_length=100, verbose_name='Nome do Titular')),
            ],
            options={
                'verbose_name': 'Detalhe Bancário da Plataforma',
                'verbose_name_plural': 'Detalhes Bancários da Plataforma',
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.URLField(help_text='O link para o grupo de WhatsApp que aparecerá no botão de apoio.', verbose_name='Link do grupo de apoio do WhatsApp')),
                ('app_download_link', models.URLField(default='https://seulinkdedownload.com', help_text='URL completa para o arquivo do aplicativo (APK, loja, etc.).', max_length=500, verbose_name='Link de Download do App')),
                ('history_text', models.TextField(help_text='O histórico da plataforma.', verbose_name="Texto da página 'Sobre'")),
                ('deposit_instruction', models.TextField(help_text='Texto que orienta o usuário sobre como fazer o depósito.', verbose_name='Texto de instrução para depósito')),
                ('withdrawal_instruction', models.TextField(help_text='Texto que explica a taxa, valor mínimo e horário de saque.', verbose_name='Texto de instrução para saque')),
            ],
            options={
                'verbose_name': 'Configuração da Plataforma',
                'verbose_name_plural': 'Configurações da Plataforma',
            },
        ),
        migrations.CreateModel(
            name='RouletteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prizes', models.CharField(blank=True, help_text='Uma lista de prêmios separados por vírgula. Ex: 100,200,500,1000', max_length=255, null=True, verbose_name='Prêmios da Roleta')),
            ],
            options={
                'verbose_name': 'Configuração da Roleta',
                'verbose_name_plural': 'Configurações da Roleta',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Telefone')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('invite_code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Disponível')),
                ('subsidy_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo de Subsídios')),
                ('level_active', models.BooleanField(default=False, verbose_name='Nível Ativo')),
                ('roulette_spins', models.IntegerField(default=0, verbose_name='Giros da Roleta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Convidado por')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('IBAN', models.CharField(max_length=50, verbose_name='IBAN')),
                ('account_holder_name', models.CharField(max_length=100, verbose_name='Nome do Titular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Detalhe Bancário do Usuário',
                'verbose_name_plural': 'Detalhes Bancários do Usuário',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('proof_of_payment', models.ImageField(upload_to='deposit_proofs/', verbose_name='Comprovativo')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prêmio')),
                ('spin_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Rodada')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Roleta',
                'verbose_name_plural': 'Roletas',
            },
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Tarefa')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('base_earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Base')),
                ('is_daily', models.BooleanField(default=True, help_text='Se marcado, o usuário só pode completar esta tarefa uma vez por dia.', verbose_name='É Diária?')),
                ('required_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.level', verbose_name='Nível Requerido')),
            ],
            options={
                'verbose_name': 'Definição de Tarefa',
                'verbose_name_plural': 'Definições de Tarefas',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganhos Registrados')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Conclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('task_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.taskdefinition', verbose_name='Definição da Tarefa')),
            ],
            options={
                'verbose_name': 'Tarefa Concluída',
                'verbose_name_plural': 'Tarefas Concluídas',
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Compra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_daily_gain_date', models.DateTimeField(blank=True, help_text='O tempo em que o último ganho de 24 horas foi aplicado. Nulo na primeira compra.', null=True, verbose_name='Data do Último Ganho Diário')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level', verbose_name='Nível')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Nível do Usuário',
                'verbose_name_plural': 'Níveis dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(default='Pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Saque',
                'verbose_name_plural': 'Saques',
            },
        ),
    ]
