# Generated by Django 5.2.5 on 2025-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlevel',
            name='last_daily_gain_date',
            field=models.DateTimeField(blank=True, help_text='O tempo em que o último ganho de 24 horas foi aplicado. Nulo na primeira compra.', null=True, verbose_name='Data do Último Ganho Diário'),
        ),
    ]
